2020-03-14 12:47:47 INFO  cn.com.alasky.StartApp 26 main - 启动应用
2020-03-14 12:47:48 INFO  org.springframework.boot.StartupInfoLogger 50 logStarting - Starting StartApp on Alasky with PID 6108 (F:\develop\association\target\classes started by Alasky in F:\develop\association)
2020-03-14 12:47:48 INFO  org.springframework.boot.SpringApplication 675 logStartupProfileInfo - No active profile set, falling back to default profiles: default
2020-03-14 12:47:49 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate 244 multipleStoresDetected - Multiple Spring Data modules found, entering strict repository configuration mode!
2020-03-14 12:47:49 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate 126 registerRepositoriesIn - Bootstrapping Spring Data repositories in DEFAULT mode.
2020-03-14 12:47:49 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate 182 registerRepositoriesIn - Finished Spring Data repository scanning in 23ms. Found 0 repository interfaces.
2020-03-14 12:47:49 INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker 330 postProcessAfterInitialization - Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$c2770b36] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-03-14 12:47:50 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer 90 initialize - Tomcat initialized with port(s): 8080 (http)
2020-03-14 12:47:50 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing ProtocolHandler ["http-nio-8080"]
2020-03-14 12:47:50 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting service [Tomcat]
2020-03-14 12:47:50 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting Servlet engine: [Apache Tomcat/9.0.16]
2020-03-14 12:47:50 INFO  org.apache.juli.logging.DirectJDKLog 173 log - The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Software\java\jdk1.8.0_211\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Software\python\Scripts\;C:\Software\python\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Software\java\jdk1.8.0_211\bin;C:\Software\java\jdk1.8.0_211\jre\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\hadoop-2.7.7\bin;%CATALINA_HOME%\lib;%CATALINA_HOME%\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Software\Git\cmd;D:\mysql-8.0.18-winx64\bin;D:\pandoc\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Software\python\python3.6\Scripts\;C:\Software\python\python3.6\;C:\Software\Scripts\;C:\Software\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\IntelliJ IDEA 2019.1.2\bin;D:\Microsoft VS Code\bin;D:\apache-maven-3.6.1\bin;C:\Software\python\Scripts;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;C:\Program Files\Bandizip\;C:\Users\Administrator\AppData\Roaming\npm;.]
2020-03-14 12:47:50 INFO  org.apache.juli.logging.DirectJDKLog 173 log - At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-03-14 12:47:50 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing Spring embedded WebApplicationContext
2020-03-14 12:47:50 INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext 296 prepareWebApplicationContext - Root WebApplicationContext: initialization completed in 2227 ms
2020-03-14 12:47:51 INFO  io.lettuce.core.EpollProvider 68 <clinit> - Starting without optional epoll library
2020-03-14 12:47:51 INFO  io.lettuce.core.KqueueProvider 70 <clinit> - Starting without optional kqueue library
2020-03-14 12:47:52 INFO  org.springframework.scheduling.concurrent.ExecutorConfigurationSupport 171 initialize - Initializing ExecutorService 'applicationTaskExecutor'
2020-03-14 12:47:53 INFO  org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor 295 finishRegistration - No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2020-03-14 12:47:53 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting ProtocolHandler ["http-nio-8080"]
2020-03-14 12:47:53 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer 204 start - Tomcat started on port(s): 8080 (http) with context path ''
2020-03-14 12:47:53 INFO  org.springframework.boot.StartupInfoLogger 59 logStarted - Started StartApp in 6.034 seconds (JVM running for 8.293)
2020-03-14 12:48:04 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-03-14 12:48:04 INFO  org.springframework.web.servlet.FrameworkServlet 524 initServletBean - Initializing Servlet 'dispatcherServlet'
2020-03-14 12:48:04 INFO  org.springframework.web.servlet.FrameworkServlet 546 initServletBean - Completed initialization in 10 ms
2020-03-14 12:48:04 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 12:48:15 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 12:48:32 INFO  com.zaxxer.hikari.HikariDataSource 110 getConnection - HikariPool-1 - Starting...
2020-03-14 12:48:33 INFO  com.zaxxer.hikari.HikariDataSource 123 getConnection - HikariPool-1 - Start completed.
2020-03-14 12:48:33 INFO  cn.com.alasky.controller.LoginController 50 getLoginInfo - 新的登录(127.0.0.1): 11122223333
2020-03-14 12:48:35 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:18:44 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:31:25 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:33:00 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:33:09 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:33:36 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:11 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:13 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:19 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:20 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:21 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:43 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:44 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:34:46 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:00 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:01 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:01 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:36 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:38 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:39 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:40 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:35:40 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:49 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:52 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:53 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:53 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:54 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:55 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:56 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:56 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:37:57 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:04 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:06 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:08 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:09 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:10 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:10 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:11 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:11 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:12 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:33 INFO  cn.com.alasky.controller.LoginController 50 getLoginInfo - 新的登录(127.0.0.1): 11122223333
2020-03-14 13:38:34 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:38:39 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:09 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:10 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:22 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:22 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:23 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:25 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:25 INFO  cn.com.alasky.controller.admin.UserDataController 36 getUserData - 查看用户信息: IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:26 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:44 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:45 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:39:46 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:02 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:03 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:03 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:04 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:11 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:16 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:17 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:18 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:18 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:19 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:40:19 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:41:01 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:49:32 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:50:49 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:51:18 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 13:51:35 INFO  cn.com.alasky.controller.LoginController 68 checkLogin - IP: 127.0.0.1 设备信息: [ Windows NT 10.0; Win64; x64 ]
2020-03-14 15:53:16 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host] Unexpected exception during request: [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host]
2020-03-14 15:53:16 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host] Unexpected exception during request: [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host]
2020-03-14 15:53:16 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-03-14 15:53:16 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-03-14 15:53:23 ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler 96 handleError - Unexpected error occurred in scheduled task. org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 200 millisecond(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.convertLettuceAccessException(LettuceSetCommands.java:520) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:245) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.sMembers(DefaultedRedisConnection.java:607) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.lambda$members$6(DefaultSetOperations.java:158) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:158) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:152) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:132) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:430) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration.lambda$configureTasks$0(RedisHttpSessionConfiguration.java:248) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 200 millisecond(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at com.sun.proxy.$Proxy97.smembers(Unknown Source) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:243) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	... 19 more

2020-03-14 15:53:26 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 15:53:26 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 15:53:26 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 15:53:26 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 15:53:26 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-03-14 15:53:26 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-03-14 15:53:27 WARN  com.zaxxer.hikari.pool.HikariPool$HouseKeeper 766 run - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1h15m53s416ms181µs700ns).
2020-03-14 16:23:47 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host] Unexpected exception during request: [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host]
2020-03-14 16:23:47 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host] Unexpected exception during request: [null, java.io.IOException: An existing connection was forcibly closed by the remote host, java.io.IOException: An existing connection was forcibly closed by the remote host]
2020-03-14 16:23:47 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-03-14 16:23:47 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-03-14 16:23:57 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 16:23:57 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 16:23:57 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 16:23:57 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 16:24:00 ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler 96 handleError - Unexpected error occurred in scheduled task. org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 200 millisecond(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.convertLettuceAccessException(LettuceSetCommands.java:520) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:245) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.sMembers(DefaultedRedisConnection.java:607) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.lambda$members$6(DefaultSetOperations.java:158) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:158) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:152) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:132) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:430) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration.lambda$configureTasks$0(RedisHttpSessionConfiguration.java:248) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 200 millisecond(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at com.sun.proxy.$Proxy97.smembers(Unknown Source) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:243) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	... 19 more

2020-03-14 16:24:07 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 16:24:07 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 16:24:07 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 16:24:07 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 16:24:17 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 16:24:17 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 16:24:17 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 16:24:17 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:08:54 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 60 SECONDS 
2020-03-14 18:08:54 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 60 SECONDS 
2020-03-14 18:08:54 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:08:54 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:08:58 WARN  com.zaxxer.hikari.pool.HikariPool$HouseKeeper 766 run - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1h45m1s908ms198µs500ns).
2020-03-14 18:09:04 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 18:09:04 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 18:09:04 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:04 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:14 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 18:09:14 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 18:09:14 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:14 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:24 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 18:09:24 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-03-14 18:09:25 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:25 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:29 WARN  io.netty.util.internal.logging.AbstractInternalLogger 199 log - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /192.168.8.101:6379 io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /192.168.8.101:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_211]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_211]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.net.SocketException: Network is unreachable: no further information
	... 11 more

2020-03-14 18:09:29 WARN  io.netty.util.internal.logging.AbstractInternalLogger 199 log - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /192.168.8.101:6379 io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: /192.168.8.101:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_211]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_211]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.net.SocketException: Network is unreachable: no further information
	... 11 more

2020-03-14 18:09:32 ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler 96 handleError - Unexpected error occurred in scheduled task. org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 200 millisecond(s)
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:268) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.convertLettuceAccessException(LettuceSetCommands.java:520) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:245) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.connection.DefaultedRedisConnection.sMembers(DefaultedRedisConnection.java:607) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.lambda$members$6(DefaultSetOperations.java:158) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:158) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:152) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:132) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:430) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration.lambda$configureTasks$0(RedisHttpSessionConfiguration.java:248) ~[spring-session-data-redis-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 200 millisecond(s)
	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:114) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:69) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80) ~[lettuce-core-5.1.4.RELEASE.jar:?]
	at com.sun.proxy.$Proxy97.smembers(Unknown Source) ~[?:?]
	at org.springframework.data.redis.connection.lettuce.LettuceSetCommands.sMembers(LettuceSetCommands.java:243) ~[spring-data-redis-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	... 19 more

2020-03-14 18:09:40 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:40 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-03-14 18:09:40 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-03-14 18:09:41 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
